### ISSUE TITLE
AttributeError in Chapter two Example one

### ISSUE THREAD

**Issue by JiaxiangBU** [PacktPublishing/hands-on-music-generation-with-magenta#1]
```python
import os

# There is a lot of useful tools in the magenta.music package,
# importing it as "mm" is pretty common in Magenta's code
import magenta.music as mm

mm.notebook_utils.download_bundle("drum_kit_rnn.mag", "bundles")
bundle = mm.sequence_generator_bundle.read_bundle_file(os.path.join("bundles", "drum_kit_rnn.mag"))
```

    WARNING:tensorflow:From D:\install\miniconda\lib\site-packages\magenta\music\notebook_utils.py:196: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.
    
    

    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-1-bcc1a6afd9b4> in <module>
          6 
          7 mm.notebook_utils.download_bundle("drum_kit_rnn.mag", "bundles")
    ----> 8 bundle = mm.sequence_generator_bundle.read_bundle_file(os.path.join("bundles", "drum_kit_rnn.mag"))
    

    AttributeError: module 'magenta.music' has no attribute 'sequence_generator_bundle'

However, I successfully install the two packages.

```python
import tensorflow
import magenta

print("Installed tensorflow version " + tensorflow.__version__)
print("Installed magenta version " + magenta.__version__)

```

    

    Installed tensorflow version 1.14.0
    Installed magenta version 1.1.2
    

I am new for the package 'magenta'.

**Comment by dubreuia** [comment]
Hello @JiaxiangBU, thanks for pointing this. Let me check it out and get back to you.

**Comment by dubreuia** [comment]
As per chapter 1 of the book, you should be using Magenta version 1.1.7, since the imports have changed since the version 1.1.2 you where using. Please follow the installation instructions from: https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/tree/master/Chapter01#installing-magenta

You should be able to upgrade using `pip install --force-reinstall magenta==1.1.7`.
