### ISSUE TITLE
how to cite this book

### ISSUE THREAD

**Issue by ruiguo-bio** [PacktPublishing/hands-on-music-generation-with-magenta#14]
Hi Alexandre, how to cite this work? I use your method for analysing the lmd-matched data in a paper, how to cite it?

**Comment by dubreuia** [comment]
Hello @ruiguo-bio, thank you for your interest in the book and the citation! :)

```
@book{book,
    author    = {DuBreuil, Alexandre},
    title     = {Hands-On Music Generation with Magenta},
    publisher = {Packt Publishing Ltd.},
    address   = {Birmingham, UK},
    year      = 2020,
    isbn      = "9781838824419"
}
```

**Comment by dubreuia** [comment]
Added to README: https://github.com/PacktPublishing/hands-on-music-generation-with-magenta#how-to-cite
