### ISSUE TITLE
Missing script: midi2plot.py

### ISSUE THREAD

**Issue by adam-suki** [PacktPublishing/hands-on-music-generation-with-magenta#15]
I assume it has been moved to dubreuia/visual_midi. 
It would make sense to leave a reference under the same filename, or update the book's reference under Ch01/Representing music with MIDI

**Comment by dubreuia** [comment]
Hello @adam-suki, thank you for your interest in the book. Indeed the TIP on page 17 is wrong, instead of

> The script for plotting a generated MIDI file can be found in the GitHub
> code for this chapter in the Chapter01/provided folder. The script is
> called midi2plot.py.

It should read

> The library VisualMIDI for plotting a generated MIDI file can be found at https://github.com/dubreuia/visual_midi. It provides a command line utility `visual_midi`.

Thank you for letter us know.

**Comment by dubreuia** [comment]
Added errata in Chapter01/provided
