### ISSUE TITLE
magenta 2.1.3 

### ISSUE THREAD

**Issue by adam-suki** [PacktPublishing/hands-on-music-generation-with-magenta#16]
Hello @dubreuia 

I'm following the book with magenta 2.1.3 where magenta.music is deprecated.
Would you mind opening a branch for this version as well? 
I'd be happy to push updated codes as I progress with the book.

**Comment by dubreuia** [comment]
Hey @adam-suki, thank you for your interest in the book. Yes I was thinking of doing that, I'll create the branch and work on it this week. Cheers

**Comment by dubreuia** [comment]
Actually, I will only support magenta@HEAD, it doesn't make sense to support old versions like 2.0.1, etc. for the book's code. I'll just create a master-magenta branch and update it to match the latest code (and tag older magenta version like 2.0.1 if necessary).

**Comment by adam-suki** [comment]
@dubreuia great to hear! If you accept contributions, it would make sense to me to also have a .md file for each chapter to take notes on the changes. I collected a few things to sent to Pack for an Errata, but most of these are not mistakes as they were true for the given version, but not anymore (e.g. magenta.music has been refactored to the note-seq package). 
It could also help to review the book for a possible second edition if you plan it.

**Comment by dubreuia** [comment]
Created https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/tree/magenta-master

**Comment by dubreuia** [comment]
> @dubreuia great to hear! If you accept contributions, it would make sense to me to also have a .md file for each chapter to take notes on the changes. I collected a few things to sent to Pack for an Errata, but most of these are not mistakes as they were true for the given version, but not anymore (e.g. magenta.music has been refactored to the note-seq package).

That would be great, I've written this article https://alexandredubreuil.com/publications/2020-06-06-music-generation-with-magenta-2-0-1-a-migration-guide-from-version-1-1-7/ for migrating from 1.1.7 to 2.0.1, but it is already outdated. 

The easiest way is to create per-chapter diff (`git diff master..magenta-v.2.1.2 Chapter01`) to show the difference between the book's code (1.1.7) and latest (current 2.1.2), maybe add some comments to explain the changes.

>  It could also help to review the book for a possible second edition if you plan it.

I'd love that but this isn't planned for now.

**Comment by dubreuia** [comment]
I'll be migrating to 2.1.2 on Chapter01 now and post the changes here

**Comment by dubreuia** [comment]
@adam-suki I've migrated all the code examples to Magenta 2.1.2 in the [`magenta-master`](https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/tree/magenta-master) branch. The code is also tagged:

- 2.1.2 - https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/releases/tag/magenta-v2.1.2
- 2.0.1 - https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/releases/tag/magenta-v2.0.1
