### ISSUE TITLE
Chapter 4 Notebook Import Utils

### ISSUE THREAD

**Issue by brenterprises** [PacktPublishing/hands-on-music-generation-with-magenta#5]
In the third code block in the Chapter 4 notebook 

```from utils import save_midi, save_plot```

should be 

```from note_sequence_utils import save_midi, save_plot```

**Comment by dubreuia** [comment]
Fixed, thanks @brenterprises, let me know if you find anything else.

**Comment by Hasterios** [comment]
does not work for me on MacOSX Catalina, magenta 2.0.1, protobuf 3.12.2, tensorflow 2.2.0

**Comment by dubreuia** [comment]
Hello @Hasterios, which branch are you using? The book was written using Magenta 1.1.7, but I've recently ported the code on Magenta 2.0.1 on https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/tree/magenta-v2.0.1.

You can also check out the README at https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/tree/magenta-v2.0.1#magenta-versioning and an article I've written on migrating to Magenta 2.0.1 for more information: https://alexandredubreuil.com/publications/2020-06-06-music-generation-with-magenta-2-0-1-a-migration-guide-from-version-1-1-7/

EDIT: this probably doesn't have anything to do with version, see https://github.com/PacktPublishing/hands-on-music-generation-with-magenta/issues/7#issuecomment-651187801

**Comment by Hasterios** [comment]
Hello Dubreuia,
Thanks you for your quickness.
I'm using Magenta 2.0.1 of course. It was installed properly following your instructions. As you see, I'm working with the notebook, and it seems that the code is exactly the same in both branches (by the way).
No idea ?
